name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: action/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the project
        run: ./gradlew assemble

      - name: Build the app
        run: ./gradlew build